#
#  This contains information for a unique instance of a robot.
#

# Name of the package to specialize
based_on_package: "picknik_ur_gazebo_config"

# Optional parameters that can be read in your launch files for specific functionality
optional_feature_params:
  gazebo_world_package_name: "picknik_ur_gazebo_scan_and_plan_config"
  gazebo_world_path: "description/simulation_worlds/scan_and_plan_world.sdf"