SetupMTCPickObject:
  approach_distance: 0.1
  arm_group_name: manipulator
  end_effector_closed_pose_name: close
  end_effector_group_name: gripper
  end_effector_name: moveit_ee
  hand_frame_name: robotiq_85_base_link
  lift_distance: 0
  world_frame_name: world
